# Generated by Django 5.2.1 on 2025-06-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_en',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_uk',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0, verbose_name='Monthly Rate'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
